// Code generated by 'go generate'; DO NOT EDIT.

package futils

import (
	"strconv"

	"github.com/ozanh/ugo"
)

// FuncPOsRe is a generated function to make ugo.CallableFunc.
// Source: func(o ugo.Object, k string) (err error)
func FuncPOsRe(fn func(ugo.Object, string) error) ugo.CallableFunc {
	return func(args ...ugo.Object) (ret ugo.Object, err error) {
		if len(args) != 2 {
			return ugo.Undefined, ugo.ErrWrongNumArguments.NewError("want=2 got=" + strconv.Itoa(len(args)))
		}

		o := args[0]
		k, ok := ugo.ToGoString(args[1])
		if !ok {
			return ugo.Undefined, ugo.NewArgumentTypeError("2nd", "string", args[1].TypeName())
		}

		err = fn(o, k)
		ret = ugo.Undefined
		return
	}
}

// FuncPORO is a generated function to make ugo.CallableFunc.
// Source: func(o ugo.Object) (ret ugo.Object)
func FuncPORO(fn func(ugo.Object) ugo.Object) ugo.CallableFunc {
	return func(args ...ugo.Object) (ret ugo.Object, err error) {
		if len(args) != 1 {
			return ugo.Undefined, ugo.ErrWrongNumArguments.NewError("want=1 got=" + strconv.Itoa(len(args)))
		}

		o := args[0]

		ret = fn(o)
		return
	}
}

// FuncPOiROe is a generated function to make ugo.CallableFunc.
// Source: func(o ugo.Object, n int) (ret ugo.Object, err error)
func FuncPOiROe(fn func(ugo.Object, int) (ugo.Object, error)) ugo.CallableFunc {
	return func(args ...ugo.Object) (ret ugo.Object, err error) {
		if len(args) != 2 {
			return ugo.Undefined, ugo.ErrWrongNumArguments.NewError("want=2 got=" + strconv.Itoa(len(args)))
		}

		o := args[0]
		n, ok := ugo.ToGoInt(args[1])
		if !ok {
			return ugo.Undefined, ugo.NewArgumentTypeError("2nd", "int", args[1].TypeName())
		}

		ret, err = fn(o, n)
		return
	}
}

// FuncPOOROe is a generated function to make ugo.CallableFunc.
// Source: func(o ugo.Object, v ugo.Object) (ret ugo.Object, err error)
func FuncPOOROe(fn func(ugo.Object, ugo.Object) (ugo.Object, error)) ugo.CallableFunc {
	return func(args ...ugo.Object) (ret ugo.Object, err error) {
		if len(args) != 2 {
			return ugo.Undefined, ugo.ErrWrongNumArguments.NewError("want=2 got=" + strconv.Itoa(len(args)))
		}

		o := args[0]
		v := args[1]

		ret, err = fn(o, v)
		return
	}
}

// FuncPOROe is a generated function to make ugo.CallableFunc.
// Source: func(o ugo.Object) (ret ugo.Object, err error)
func FuncPOROe(fn func(ugo.Object) (ugo.Object, error)) ugo.CallableFunc {
	return func(args ...ugo.Object) (ret ugo.Object, err error) {
		if len(args) != 1 {
			return ugo.Undefined, ugo.ErrWrongNumArguments.NewError("want=1 got=" + strconv.Itoa(len(args)))
		}

		o := args[0]

		ret, err = fn(o)
		return
	}
}

// FuncPiROe is a generated function to make ugo.CallableFunc.
// Source: func(i1 int) (ret ugo.Object, err error)
func FuncPiROe(fn func(int) (ugo.Object, error)) ugo.CallableFunc {
	return func(args ...ugo.Object) (ret ugo.Object, err error) {
		if len(args) != 1 {
			return ugo.Undefined, ugo.ErrWrongNumArguments.NewError("want=1 got=" + strconv.Itoa(len(args)))
		}

		i1, ok := ugo.ToGoInt(args[0])
		if !ok {
			return ugo.Undefined, ugo.NewArgumentTypeError("1st", "int", args[0].TypeName())
		}

		ret, err = fn(i1)
		return
	}
}

// FuncPi64ROe is a generated function to make ugo.CallableFunc.
// Source: func(i1 int64) (ret ugo.Object, err error)
func FuncPi64ROe(fn func(int64) (ugo.Object, error)) ugo.CallableFunc {
	return func(args ...ugo.Object) (ret ugo.Object, err error) {
		if len(args) != 1 {
			return ugo.Undefined, ugo.ErrWrongNumArguments.NewError("want=1 got=" + strconv.Itoa(len(args)))
		}

		i1, ok := ugo.ToGoInt64(args[0])
		if !ok {
			return ugo.Undefined, ugo.NewArgumentTypeError("1st", "int", args[0].TypeName())
		}

		ret, err = fn(i1)
		return
	}
}

// FuncPsROe is a generated function to make ugo.CallableFunc.
// Source: func(s string) (ret ugo.Object, err error)
func FuncPsROe(fn func(string) (ugo.Object, error)) ugo.CallableFunc {
	return func(args ...ugo.Object) (ret ugo.Object, err error) {
		if len(args) != 1 {
			return ugo.Undefined, ugo.ErrWrongNumArguments.NewError("want=1 got=" + strconv.Itoa(len(args)))
		}

		s, ok := ugo.ToGoString(args[0])
		if !ok {
			return ugo.Undefined, ugo.NewArgumentTypeError("1st", "string", args[0].TypeName())
		}

		ret, err = fn(s)
		return
	}
}

// FuncPsi64ROe is a generated function to make ugo.CallableFunc.
// Source: func(s string, i1 int64) (ret ugo.Object, err error)
func FuncPsi64ROe(fn func(string, int64) (ugo.Object, error)) ugo.CallableFunc {
	return func(args ...ugo.Object) (ret ugo.Object, err error) {
		if len(args) != 2 {
			return ugo.Undefined, ugo.ErrWrongNumArguments.NewError("want=2 got=" + strconv.Itoa(len(args)))
		}

		s, ok := ugo.ToGoString(args[0])
		if !ok {
			return ugo.Undefined, ugo.NewArgumentTypeError("1st", "string", args[0].TypeName())
		}
		i1, ok := ugo.ToGoInt64(args[1])
		if !ok {
			return ugo.Undefined, ugo.NewArgumentTypeError("2nd", "int", args[1].TypeName())
		}

		ret, err = fn(s, i1)
		return
	}
}

// FuncPRO is a generated function to make ugo.CallableFunc.
// Source: func() (ret ugo.Object)
func FuncPRO(fn func() ugo.Object) ugo.CallableFunc {
	return func(args ...ugo.Object) (ret ugo.Object, err error) {
		if len(args) != 0 {
			return ugo.Undefined, ugo.ErrWrongNumArguments.NewError("want=0 got=" + strconv.Itoa(len(args)))
		}

		ret = fn()
		return
	}
}

// FuncPi64i64RO is a generated function to make ugo.CallableFunc.
// Source: func(i1 int64, i2 int64) (ret ugo.Object)
func FuncPi64i64RO(fn func(int64, int64) ugo.Object) ugo.CallableFunc {
	return func(args ...ugo.Object) (ret ugo.Object, err error) {
		if len(args) != 2 {
			return ugo.Undefined, ugo.ErrWrongNumArguments.NewError("want=2 got=" + strconv.Itoa(len(args)))
		}

		i1, ok := ugo.ToGoInt64(args[0])
		if !ok {
			return ugo.Undefined, ugo.NewArgumentTypeError("1st", "int", args[0].TypeName())
		}
		i2, ok := ugo.ToGoInt64(args[1])
		if !ok {
			return ugo.Undefined, ugo.NewArgumentTypeError("2nd", "int", args[1].TypeName())
		}

		ret = fn(i1, i2)
		return
	}
}

// FuncPb2RO is a generated function to make ugo.CallableFunc.
// Source: func(b []byte) (ret ugo.Object)
func FuncPb2RO(fn func([]byte) ugo.Object) ugo.CallableFunc {
	return func(args ...ugo.Object) (ret ugo.Object, err error) {
		if len(args) != 1 {
			return ugo.Undefined, ugo.ErrWrongNumArguments.NewError("want=1 got=" + strconv.Itoa(len(args)))
		}

		b, ok := ugo.ToGoByteSlice(args[0])
		if !ok {
			return ugo.Undefined, ugo.NewArgumentTypeError("1st", "bytes", args[0].TypeName())
		}

		ret = fn(b)
		return
	}
}

// FuncPOssRO is a generated function to make ugo.CallableFunc.
// Source: func(o ugo.Object, s1 string, s2 string) (ret ugo.Object)
func FuncPOssRO(fn func(ugo.Object, string, string) ugo.Object) ugo.CallableFunc {
	return func(args ...ugo.Object) (ret ugo.Object, err error) {
		if len(args) != 3 {
			return ugo.Undefined, ugo.ErrWrongNumArguments.NewError("want=3 got=" + strconv.Itoa(len(args)))
		}

		o := args[0]
		s1, ok := ugo.ToGoString(args[1])
		if !ok {
			return ugo.Undefined, ugo.NewArgumentTypeError("2nd", "string", args[1].TypeName())
		}
		s2, ok := ugo.ToGoString(args[2])
		if !ok {
			return ugo.Undefined, ugo.NewArgumentTypeError("3rd", "string", args[2].TypeName())
		}

		ret = fn(o, s1, s2)
		return
	}
}

// FuncPb2bRO is a generated function to make ugo.CallableFunc.
// Source: func(p []byte, b bool) (ret ugo.Object)
func FuncPb2bRO(fn func([]byte, bool) ugo.Object) ugo.CallableFunc {
	return func(args ...ugo.Object) (ret ugo.Object, err error) {
		if len(args) != 2 {
			return ugo.Undefined, ugo.ErrWrongNumArguments.NewError("want=2 got=" + strconv.Itoa(len(args)))
		}

		p, ok := ugo.ToGoByteSlice(args[0])
		if !ok {
			return ugo.Undefined, ugo.NewArgumentTypeError("1st", "bytes", args[0].TypeName())
		}
		b, ok := ugo.ToGoBool(args[1])
		if !ok {
			return ugo.Undefined, ugo.NewArgumentTypeError("2nd", "bool", args[1].TypeName())
		}

		ret = fn(p, b)
		return
	}
}
